import React, { useState, useRef, useEffect } from 'react';
import { Send, Sparkles, ChevronDown } from 'lucide-react';
import { askEuclides } from '../services/gemini';
import { Workspace, Point, GeometricShape } from '../types';
import { generateId } from '../utils/geometry';
import clsx from 'clsx';
import ReactMarkdown from 'react-markdown';

interface ChatProps {
  activeWorkspace: Workspace;
  setPoints: React.Dispatch<React.SetStateAction<Record<string, Point>>>;
  setShapes: React.Dispatch<React.SetStateAction<GeometricShape[]>>;
  isOpen: boolean;
  onClose: () => void;
}

interface ChatMessage {
  role: 'user' | 'assistant';
  text: string;
}

const Chat: React.FC<ChatProps> = ({ activeWorkspace, setPoints, setShapes, isOpen, onClose }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: 'assistant', text: 'Saudações, estudante. Sou **Euclides**. O quadro está à vossa disposição. Desejas que eu demonstre a *Proposição 1* dos Elementos, ou preferes que eu analise vossas construções atuais?' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isOpen]);

  // --- Tool Execution Logic ---

  const executeFunctionCalls = (functionCalls: any[]) => {
    if (!functionCalls || functionCalls.length === 0) return;

    // Temporary mapping for IDs generated by AI (e.g., "p1") to Real IDs (e.g., "ab3d9s")
    const idMap: Record<string, string> = {};

    functionCalls.forEach(fc => {
      const args = fc.args;
      
      if (fc.name === 'create_point') {
        const realId = generateId();
        const aiId = args.id; 
        
        if (aiId) idMap[aiId] = realId;

        setPoints(prev => ({
          ...prev,
          [realId]: {
            id: realId,
            x: Number(args.x),
            y: Number(args.y),
            label: args.label || ''
          }
        }));
      }

      if (fc.name === 'create_shape') {
        const p1 = idMap[args.p1_id] || args.p1_id; 
        const p2 = idMap[args.p2_id] || args.p2_id;

        if (p1 && p2) {
            setShapes(prev => [
              ...prev,
              {
                id: generateId(),
                type: args.type,
                p1: p1,
                p2: p2
              }
            ]);
        }
      }

      if (fc.name === 'clear_board') {
        setPoints({});
        setShapes([]);
      }
    });
  };

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMsg = input;
    setInput('');
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setIsLoading(true);

    try {
      // Send current workspace context to Gemini
      const response = await askEuclides(userMsg, activeWorkspace);
      
      if (response.text) {
        setMessages(prev => [...prev, { role: 'assistant', text: response.text }]);
      }

      if (response.functionCalls && response.functionCalls.length > 0) {
        executeFunctionCalls(response.functionCalls);
        
        if (!response.text) {
             setMessages(prev => [...prev, { role: 'assistant', text: '*Traçando as linhas necessárias no papiro digital...*' }]);
        }
      }

    } catch (error) {
      setMessages(prev => [...prev, { role: 'assistant', text: 'Perdoe-me, houve uma perturbação no raciocínio lógico.' }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className={clsx(
      "fixed bottom-6 right-24 z-20 transition-all duration-300 flex flex-col shadow-2xl rounded-2xl border border-slate-200 bg-white w-96 h-[600px]",
      isOpen ? "translate-y-0 opacity-100 pointer-events-auto" : "translate-y-8 opacity-0 pointer-events-none"
    )}>
      {/* Header */}
      <div 
        className="bg-indigo-900 text-white p-4 flex items-center justify-between rounded-t-2xl cursor-default"
      >
        <div className="flex items-center gap-2">
          <Sparkles size={20} className="text-amber-200" />
          <div>
            <span className="font-semibold block leading-tight">O Geômetra</span>
            <span className="text-[10px] text-indigo-200 uppercase tracking-widest">Alexandria AI</span>
          </div>
        </div>
        <button 
          onClick={onClose}
          className="hover:bg-indigo-800 p-1 rounded-full transition-colors"
        >
          <ChevronDown size={20} />
        </button>
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-50">
        {messages.map((msg, idx) => (
          <div 
            key={idx} 
            className={clsx(
              "max-w-[85%] p-3 rounded-2xl text-sm leading-relaxed shadow-sm",
              msg.role === 'user' 
                ? "ml-auto bg-indigo-600 text-white rounded-br-none" 
                : "mr-auto bg-white text-slate-800 border border-slate-200 rounded-bl-none font-serif"
            )}
          >
            <ReactMarkdown>{msg.text}</ReactMarkdown>
          </div>
        ))}
        {isLoading && (
          <div className="flex gap-1 items-center ml-2 text-slate-400 text-xs">
              <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0s' }}></div>
              <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
              <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-3 bg-white border-t border-slate-100 flex gap-2">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          placeholder="Pergunte ao mestre..."
          className="flex-1 bg-slate-100 border-none rounded-xl px-4 py-2 text-sm focus:ring-2 focus:ring-indigo-900 focus:outline-none placeholder:text-slate-400"
        />
        <button 
          onClick={handleSend}
          disabled={!input.trim() || isLoading}
          className="bg-indigo-900 hover:bg-indigo-800 disabled:opacity-50 disabled:cursor-not-allowed text-white p-2 rounded-xl transition-colors flex items-center justify-center w-10 h-10"
        >
          <Send size={18} />
        </button>
      </div>
    </div>
  );
};

export default Chat;