import { useState } from 'react';
import { askEuclides, GeminiResponse } from '../services/gemini';
import { Workspace, Point, GeometricShape } from '../types';
import { generateId } from '../utils/geometry';

export interface ChatMessage {
    role: 'user' | 'assistant';
    text: string;
}

interface UseChatProps {
    activeWorkspace: Workspace;
    setPoints: React.Dispatch<React.SetStateAction<Record<string, Point>>>;
    setShapes: React.Dispatch<React.SetStateAction<GeometricShape[]>>;
}

export const useChat = ({ activeWorkspace, setPoints, setShapes }: UseChatProps) => {
    const [messages, setMessages] = useState<ChatMessage[]>([
        { role: 'assistant', text: 'Saudações, estudante. Sou **Euclides**. O quadro está à vossa disposição. Desejas que eu demonstre a *Proposição 1* dos Elementos, ou preferes que eu analise vossas construções atuais?' }
    ]);
    const [isLoading, setIsLoading] = useState(false);

    const executeFunctionCalls = (functionCalls: any[]) => {
        if (!functionCalls || functionCalls.length === 0) return;
    
        // Temporary mapping for IDs generated by AI (e.g., "p1") to Real IDs (e.g., "ab3d9s")
        const idMap: Record<string, string> = {};
    
        functionCalls.forEach(fc => {
          const args = fc.args;
          
          if (fc.name === 'create_point') {
            const realId = generateId();
            const aiId = args.id; 
            
            if (aiId) idMap[aiId] = realId;
    
            setPoints(prev => ({
              ...prev,
              [realId]: {
                id: realId,
                x: Number(args.x),
                y: Number(args.y),
                label: args.label || ''
              }
            }));
          }
    
          if (fc.name === 'create_shape') {
            const p1 = idMap[args.p1_id] || args.p1_id; 
            const p2 = idMap[args.p2_id] || args.p2_id;
    
            if (p1 && p2) {
                setShapes(prev => [
                  ...prev,
                  {
                    id: generateId(),
                    type: args.type,
                    p1: p1,
                    p2: p2
                  }
                ]);
            }
          }
    
          if (fc.name === 'clear_board') {
            setPoints({});
            setShapes([]);
          }
        });
    };

    const sendMessage = async (input: string) => {
        if (!input.trim() || isLoading) return;
    
        setMessages(prev => [...prev, { role: 'user', text: input }]);
        setIsLoading(true);
    
        try {
          const response: GeminiResponse = await askEuclides(input, activeWorkspace);
          
          if (response.text) {
            setMessages(prev => [...prev, { role: 'assistant', text: response.text }]);
          }
    
          if (response.functionCalls && response.functionCalls.length > 0) {
            executeFunctionCalls(response.functionCalls);
            
            if (!response.text) {
                 setMessages(prev => [...prev, { role: 'assistant', text: '*Traçando as linhas necessárias no papiro digital...*' }]);
            }
          }
    
        } catch (error) {
          setMessages(prev => [...prev, { role: 'assistant', text: 'Perdoe-me, houve uma perturbação no raciocínio lógico.' }]);
        } finally {
          setIsLoading(false);
        }
    };

    return { messages, isLoading, sendMessage };
};